name: simple-rl-agent
channels:
  - conda-forge
dependencies:
  - python=3.12.11
  - pip=25.2
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - torchaudio==2.8.0
      - tensorboard==2.20.0
      - tensorboardx==2.6.4
      - tqdm
      - matplotlib
      - wandb
